#!/bin/sh

#  Copyleft:    CodeASAP.pl
#  LICENSE:     CC BY-SA 4.0
#
#  E - espeaks what cat says

set -eu

# Program options
Language=${1:-el}


echo "#" $Language $(date -R)
echo

# Program
rlwrap -H ~/.espeak.history.$Language.txt cat | egrep -v '^#' --line-buffered | espeak -v $Language
